require 'rubygems'  
require 'rake'  
require 'echoe'  
  
Echoe.new('s3ify', '0.1.0') do |p|  
  p.description     = "Repair the link generated by Paperclip to transform for European buckets only"  
  p.url             = "http://github.com/elimayost/s3ify"  
  p.author          = "Eli Mayost"  
  p.email           = "eli.mayost@googlemail.com"  
  p.ignore_pattern  = ["tmp/*", "script/*"]  
  p.development_dependencies = []  
end  
  
Dir["#{File.dirname(__FILE__)}/tasks/*.rake"].sort.each { |ext| load ext }  